In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import warnings
warnings.filterwarnings('ignore')


In [2]:
print(os.getcwd())


C:\Users\Asus\OneDrive\Desktop\PRJ Car Price Prediction


In [3]:
os.chdir(r"C:\Users\Asus\OneDrive\Desktop\PRJ Car Price Prediction")
print(os.getcwd())


C:\Users\Asus\OneDrive\Desktop\PRJ Car Price Prediction


In [4]:
df = pd.read_csv("audi.csv")
df


model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0        A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2        A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4        A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0
...     ...   ...    ...          ...      ...      ...  ...   ...         ...
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6         1.0
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6         1.0
10665    A3  2020  17199       Manual      609   Petrol  150  49.6         1.0
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9         1.4
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9         1.4

[10668 rows x 9 columns]

In [5]:
import ydata_profiling as pf
pf.ProfileReport(df)


Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]


100%|████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 121.06it/s]


Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [6]:
len(df)


10668

In [7]:
df.shape


(10668, 9)

In [8]:
df.dtypes


model            object
year              int64
price             int64
transmission     object
mileage           int64
fuelType         object
tax               int64
mpg             float64
engineSize      float64
dtype: object

In [9]:
df.isna().sum()


model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [10]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10668 entries, 0 to 10667
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         10668 non-null  object 
 1   year          10668 non-null  int64  
 2   price         10668 non-null  int64  
 3   transmission  10668 non-null  object 
 4   mileage       10668 non-null  int64  
 5   fuelType      10668 non-null  object 
 6   tax           10668 non-null  int64  
 7   mpg           10668 non-null  float64
 8   engineSize    10668 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 750.2+ KB


In [11]:
df[df.duplicated()]


model  year  price transmission  mileage fuelType  tax   mpg  engineSize
273     Q3  2019  34485    Automatic       10   Diesel  145  47.1         2.0
764     Q2  2019  22495       Manual     1000   Diesel  145  49.6         1.6
784     Q3  2015  13995       Manual    35446   Diesel  145  54.3         2.0
967     Q5  2019  31998    Semi-Auto      100   Petrol  145  33.2         2.0
990     Q2  2019  22495       Manual     1000   Diesel  145  49.6         1.6
...    ...   ...    ...          ...      ...      ...  ...   ...         ...
9508    A4  2019  26990    Automatic     2250   Diesel  145  50.4         2.0
9521    Q3  2019  26990       Manual       10   Petrol  145  40.9         1.5
9529    Q5  2019  44990    Automatic       10   Diesel  145  36.2         2.0
9550    Q3  2019  29995       Manual       10   Petrol  145  39.8         1.5
9597    Q3  2019  28490       Manual       10   Diesel  145  42.8         2.0

[103 rows x 9 columns]

In [12]:
df.describe()


year          price        mileage           tax           mpg  \
count  10668.000000   10668.000000   10668.000000  10668.000000  10668.000000   
mean    2017.100675   22896.685039   24827.244001    126.011436     50.770022   
std        2.167494   11714.841888   23505.257205     67.170294     12.949782   
min     1997.000000    1490.000000       1.000000      0.000000     18.900000   
25%     2016.000000   15130.750000    5968.750000    125.000000     40.900000   
50%     2017.000000   20200.000000   19000.000000    145.000000     49.600000   
75%     2019.000000   27990.000000   36464.500000    145.000000     58.900000   
max     2020.000000  145000.000000  323000.000000    580.000000    188.300000   

         engineSize  
count  10668.000000  
mean       1.930709  
std        0.602957  
min        0.000000  
25%        1.500000  
50%        2.000000  
75%        2.000000  
max        6.300000

In [13]:
X = df.iloc[:, [0,1,3,4,5,6,7,8]].values
Y = df.iloc[:, [2]].values

X.shape, Y.shape


((10668, 8), (10668, 1))

In [14]:
from sklearn.preprocessing import LabelEncoder

le1 = LabelEncoder()
X[:, 0] = le1.fit_transform(X[:, 0])   # model column

le2 = LabelEncoder()
X[:, -4] = le2.fit_transform(X[:, -4])  # fuelType column

X


array([[0, 2017, 'Manual', ..., 150, 55.4, 1.4],
       [5, 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [0, 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [2, 2020, 'Manual', ..., 150, 49.6, 1.0],
       [9, 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [9, 2016, 'Manual', ..., 150, 47.9, 1.4]],
      shape=(10668, 8), dtype=object)

In [15]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [2])],
    remainder='passthrough'
)

X = ct.fit_transform(X)
X.shape


(10668, 10)

In [16]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)

X


array([[-0.58326752,  1.2007284 , -0.71233307, ...,  0.35714729,
         0.35755001, -0.88021837],
       [ 1.71447913, -0.83282781, -0.71233307, ..., -1.57832278,
         1.03713001,  0.11492465],
       [-0.58326752,  1.2007284 , -0.71233307, ..., -1.42944047,
         0.35755001, -0.88021837],
       ...,
       [-0.58326752,  1.2007284 , -0.71233307, ...,  0.35714729,
        -0.09035499, -1.54364705],
       [ 1.71447913, -0.83282781, -0.71233307, ...,  0.35714729,
        -0.22163749, -0.88021837],
       [-0.58326752,  1.2007284 , -0.71233307, ...,  0.35714729,
        -0.22163749, -0.88021837]], shape=(10668, 10))

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=0
)

X_train.shape, X_test.shape, Y_train.shape, Y_test.shape


((8534, 10), (2134, 10), (8534, 1), (2134, 1))

In [18]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(random_state=0)
rf.fit(X_train, Y_train)


RandomForestRegressor(random_state=0)

In [19]:
y_pred = rf.predict(X_test)
y_pred


array([14337.15, 23450.35, 27330.07, ..., 46275.18, 31359.  ,  9929.62],
      shape=(2134,))

In [20]:
from sklearn.metrics import r2_score, mean_absolute_error

print("R2 Score:", r2_score(Y_test, y_pred))
print("Mean Absolute Error:", mean_absolute_error(Y_test, y_pred))


R2 Score: 0.9536134841307546
Mean Absolute Error: 1538.730980670462


In [21]:
import pandas as pd

comparison = pd.concat([
    pd.DataFrame(Y_test, columns=['Actual Price']),
    pd.DataFrame(y_pred, columns=['Predicted Price'])
], axis=1)

comparison.head(10)


Actual Price  Predicted Price
0         14998     14337.150000
1         21950     23450.350000
2         28990     27330.070000
3         25489     27200.980000
4         30950     32250.050000
5         30299     28257.477500
6         14498     15802.250000
7         32000     33246.169527
8         19991     19913.880524
9         29990     29092.650000

In [22]:
full_pred = rf.predict(X)
full_pred


array([12864.85, 16457.12, 11755.03, ..., 17642.77, 20217.97, 18360.66],
      shape=(10668,))

In [23]:
print("R2 Score (Full Data):", r2_score(Y, full_pred))
print("MAE (Full Data):", mean_absolute_error(Y, full_pred))


R2 Score (Full Data): 0.9854936957854944
MAE (Full Data): 784.8616110361776


In [24]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression()
reg.fit(X_train, Y_train)

print(reg)


LinearRegression()


In [25]:
y_pred_lr = reg.predict(X_test)
y_pred_lr


array([[13052.36575395],
       [29340.03009442],
       [31908.12716369],
       ...,
       [42649.94612604],
       [31554.51438191],
       [ 7285.29079975]], shape=(2134, 1))

In [26]:
print(pd.concat([
    pd.DataFrame(Y_test, columns=['Car Price']),
    pd.DataFrame(y_pred_lr, columns=['Price Prediction'])
], axis=1))


      Car Price  Price Prediction
0         14998      13052.365754
1         21950      29340.030094
2         28990      31908.127164
3         25489      26834.582322
4         30950      31477.717507
...         ...               ...
2129      23700      41546.889475
2130      18000      20705.470993
2131      45995      42649.946126
2132      30500      31554.514382
2133       8400       7285.290800

[2134 rows x 2 columns]


In [27]:
from sklearn.metrics import r2_score, mean_absolute_error

print("R2 Score:", r2_score(Y_test, y_pred_lr))
print("Mean Absolute Error:", mean_absolute_error(Y_test, y_pred_lr))


R2 Score: 0.7916214142758097
Mean Absolute Error: 3381.6733395890574


In [28]:
f_pred_lr = reg.predict(X)

result = pd.concat(
    [df, pd.DataFrame(f_pred_lr, columns=['Price Prediction'])],
    axis=1
)
result.head()


model  year  price transmission  mileage fuelType  tax   mpg  engineSize  \
0    A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4   
1    A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0   
2    A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4   
3    A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0   
4    A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0   

   Price Prediction  
0      14619.723522  
1      20635.866607  
2      13800.630701  
3      19914.076834  
4      17339.679474

In [29]:
print("R2 Score:", r2_score(Y, f_pred_lr))
print("Mean Absolute Error:", mean_absolute_error(Y, f_pred_lr))


R2 Score: 0.7907188149740701
Mean Absolute Error: 3344.0465070147598


In [30]:
from sklearn.ensemble import ExtraTreesRegressor

ET_Model = ExtraTreesRegressor(n_estimators=120)
ET_Model.fit(X_train, Y_train)


ExtraTreesRegressor(n_estimators=120)

In [31]:
et_pred = ET_Model.predict(X_test)

print("R2 Score:", r2_score(Y_test, et_pred))
print("Mean Absolute Error:", mean_absolute_error(Y_test, et_pred))


R2 Score: 0.957138276856427
Mean Absolute Error: 1542.4496416484433


In [32]:
f_pred_et = ET_Model.predict(X)

result = pd.concat(
    [df, pd.DataFrame(f_pred_et, columns=['Price Prediction'])],
    axis=1
)
result.head()


model  year  price transmission  mileage fuelType  tax   mpg  engineSize  \
0    A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4   
1    A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0   
2    A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4   
3    A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0   
4    A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0   

   Price Prediction  
0           12500.0  
1           16500.0  
2           11000.0  
3           16800.0  
4           17300.0

In [33]:
print("R2 Score:", r2_score(Y, f_pred_et))
print("Mean Absolute Error:", mean_absolute_error(Y, f_pred_et))


R2 Score: 0.9905117478421703
Mean Absolute Error: 351.31387188580595


In [34]:
from catboost import CatBoostRegressor

cat = CatBoostRegressor(verbose=False)
cat.fit(X_train, Y_train)


In [35]:
from catboost import CatBoostRegressor

cat = CatBoostRegressor(verbose=False)
cat.fit(X_train, Y_train)

In [36]:
import pickle

pickle.dump(cat, open('model.pkl', 'wb'))


In [37]:
model = pickle.load(open('model.pkl', 'rb'))
p_pred = model.predict(X)

p_pred


array([13989.8267214 , 16578.03846793, 12489.54800057, ...,
       18716.55396652, 20908.57305802, 17896.99245815], shape=(10668,))

In [38]:
result = pd.concat(
    [df, pd.DataFrame(p_pred, columns=['Price Prediction'])],
    axis=1
)

result.head()


model  year  price transmission  mileage fuelType  tax   mpg  engineSize  \
0    A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4   
1    A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0   
2    A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4   
3    A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0   
4    A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0   

   Price Prediction  
0      13989.826721  
1      16578.038468  
2      12489.548001  
3      18793.884463  
4      18493.205301

In [39]:
from sklearn.metrics import r2_score, mean_absolute_error

print("R2 Score:", r2_score(Y, p_pred))
print("Mean Absolute Error:", mean_absolute_error(Y, p_pred))


R2 Score: 0.9745608180217411
Mean Absolute Error: 1300.9813014378083
